### PR TITLE
feat: ✨ add a single-action mode for combat tracker

### PR DESCRIPTION
**Pull request by ben**
## Summary
This mimics the slow-and-fast-actions settings option to provide a Dragonbane-friendly setup with a single action button.

CleanShot 2024-02-04 at 11 47 51
CleanShot 2024-02-04 at 11 46 32
CleanShot 2024-02-04 at 11 45 55 

### PR Type

- [ ] This PR is a code change that implements a feature request.
- [x] This PR adds a new feature that is not an open feature request.
- [ ] This PR fixes an issue.
- [ ] This PR is not a code change (e.g. documentation, README, ...)

### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by ben** [comment]
It's possible that two separate checkboxes isn't the right way to represent these modes any longer. Maybe a select box called "Additional combat tracker buttons", with options "none", "single action" and "fast and slow actions" would be better. Let me know if that's what you'd prefer, and I'm happy to update the PR to do that.

**Comment by Cussa** [comment]
There is another PR #38 that is connecting the Slow and Fast action to the tokens, but that is still open. Maybe it would worth to wait that one, as that can impact on the behaviour of this one. (Or maybe this is already using the methods that are changed by the other, but I just wanted to leave the heads-up)

**Comment by ben** [comment]
Saw that #38 got merged, so I rebuilt this one, and it's ready for another look.

**Review by aMediocreDad — APPROVED** [review]
Great work, thank you!

**Pull request merged**
